name: cron-schedule

on: 
    schedule:
        - cron: "*/5 * * * *" 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Build the code
                run: echo "Building the code..."