name: demo-workflow
on: push
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Welcome Message
          run: echo "Welcome to my demo workflow!"
