name: test-workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: List Files with Details
        run: ls -ltra
      
      - name: Welcome Message
        run: |
          chmod +x ./scripts/welcome.sh
          ./scripts/welcome.sh
            

      - name: Print ASCII Art
        run: |
          chmod +x ./scripts/print-ascii.sh
          ./scripts/print-ascii.sh