name: test-workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Welcome Message
        run: |
            echo "My First git hub action job"
            ls -la
            cat README.md

      - name : Install cowsay
        run: sudo apt-get install cowsay

      - name: ASCII art
        run: cowsay -f dragon "Hahahah, I am Dragon....RAWR!!!" >> dragon.txt