name: test-workflow
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Welcome Message
        run: ./scripts/welcome.sh
            

      - name: Print ASCII Art
        run: ./scripts/print-ascii.sh