name: Variables
on: push
env:
    CONTAINER_NAME: test-docker-container
    DOCKER_IMAGE_NAME: test-docker-image
jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            DOCKER_USERNAME: abhishek_b
        steps:
            -   name: Docker Build
                run: echo docker build -t ${{ env.CONTAINER_NAME }}/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest
            
            -   name: Docker Login
                env:
                    DOCKER_PASSWORD: abhishek1234
                run: echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            -   name: Docker Publish
                run: echo docker push $CONTAINER_NAME/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest

            -   name: Docker Status check
                run: echo "Docker image $CONTAINER_NAME/$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:latest has been built and pushed successfully!"
    
    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
            -   name: Deploying the code
                run: echo "Deploying the code..."
            
            -   name: Docker Run
                run: echo docker run -d $CONTAINER_NAME/$DOCKER_IMAGE_NAME:latest