name: workflow-concurrency
on: push

concurrency:
  group: workflow-concurrency-group
  cancel-in-progress: true

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Docker Build
                run: echo docker build -t $CONTAINER_NAME/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest
            
            -   name: Docker Login
                run: echo docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            -   name: Docker Publish
                run: echo docker push $CONTAINER_NAME/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest

            -   name: Docker Status check
                run: echo "Docker image $CONTAINER_NAME/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME:latest has been built and pushed successfully!"
    
    deploy:
        runs-on: ubuntu-latest
        concurrency:
            group: deploy-group
            cancel-in-progress: true
        needs: docker
        steps:
            -   name: Deploying the code
                run: echo "Deploying the code..."
            
            -   name: Docker Run
                run: echo docker run -d $CONTAINER_NAME/$DOCKER_IMAGE_NAME:latest

            -   name: Concurrency Check
                run: |
                    echo "Checking for concurrent deployments..."
                    sleep 180